name: Ivan Križnar
description: "Web developer with more than 10 years of experience building exceptional websites and services."
meta_description: "Adventures in web development"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
paginate_path: '/blog/:num/'
baseurl: '/'
blogurl: '/blog'
domain_name: 'http://simplified.me'
google_analytics: 'UA-267787-27'

# Details for the RSS feed generator
url:            'http://simplified.me'
author:         'Ivan Križnar'

exclude: [ Gemfile, Gemfile.lock, Procfile, vendor, gems]
